# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
# â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â•šâ•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•”â•â•â•â•â•
# â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—  â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—  
# â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•”â•â•â•  â–ˆâ–ˆâ•”â•â•â•  
# â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
# â•šâ•â•  â•šâ•â•   â•šâ•â•   â•šâ•â•  â•šâ•â•â•šâ•â•â•â•â•â•â•â•šâ•â•â•â•â•â•â•
#
# rtree is a customizable tree command built in Rust
# with support for icons and colors.
# By: @johanx22x

# customizable settings
# each option is also available as a command line flag
[config]
color = true # enable colored output
icons = true # enable icons
dot_ignore = true # ignore dot files
less_like = false # use less like output
dir_only = false # only show directories
size = false # show file sizes

# compress settings
compress = true # compress output (set a limit for the amount of files shown per folder)
compress_amount = 5 # amount of files per folder
dir_compress = false # if compress is enabled, compress directories as well
dir_amount = 5 # amount of directories per folder

# depth settings
depth_limit = false # limit the depth of the tree
depth = 5 # depth limit

# name compression settings
name_compress = false # compress names 
name_limit = 10 # amount of characters to show

# colors
[colors]
ln = "0;36" # lINK
or = "0;36" # ORPHAN
tw = "0;36" # STICKY_OTHER_WRITABLE
ow = "0;36" # OTHER_WRITABLE
st = "0;36" # STICKY 
di = "0;36" # DIR 
pi = "0;36" # FIFO 
so = "0;36" # SOCK 
bd = "0;36" # BLK 
cd = "0;36" # CHR 
su = "0;36" # SETUID 
sg = "0;36" # SETGID 
ex = "0;36" # EXEC 
fi = "0;36" # FILE 

# mandatory file types
[file_type]
ln = "ï’" # lINK
or = "ï‘§" # ORPHAN
tw = "ó°Œª" # STICKY_OTHER_WRITABLE
ow = "ó°‰’" # OTHER_WRITABLE
st = "ó°“¹" # STICKY 
di = "ï¼" # DIR 
pi = "î®¢" # FIFO 
so = "ó°¤…" # SOCK 
bd = "ó±Šˆ" # BLK 
cd = "ó°¿º" # CHR
su = "ï‹ƒ" # SETUID
sg = "ï“½" # SETGID
ex = "ï‘±" # EXEC
fi = "ï’¥" # FILE

# icons
# custom icons are matched using regex
[icons]
"\\.styl" = "î˜€"
"\\.sass" = "î˜ƒ"
"\\.scss" = "î˜ƒ"
"\\.htm" = "ï„»"
"\\.html" = "ï„»"
"\\.xhtml" = "ï„»"
"\\.shtml" = "ï„»"
"\\.slim" = "î˜"
"\\.haml" = "î˜"
"\\.ejs" = "î˜"
"\\.css" = "î‰"
"\\.qss" = "î˜”"
"\\.rasi" = "î˜”"
"\\.less" = "î˜”"
"\\.wiki" = "ï‰¦"
"\\.md" = "îœ¾"
"\\.mdx" = "îœ¾"
"\\.markdown" = "îœ¾"
"\\.rmd" = "îœ¾"
"\\.Rmd" = "îœ¾"
"\\.xml" = "ïœ­"
"\\.json" = "î˜‹"
"\\.bson" = "î˜‹"
"\\.webmanifest" = "î˜‹"
"\\.js" = "î"
"\\.mjs" = "î"
"\\.jsx" = "îº"
"\\.rb" = "î‘"
"\\.gemspec" = "î‘"
"\\.rake" = "î‘"
"\\.php" = "îœ½"
"\\.py" = "î˜†"
"\\.pyc" = "î˜†"
"\\.pyo" = "î˜†"
"\\.pyd" = "î˜†"
"\\.ipynb" = "î˜†"
"\\.nim" = "ğŸ‘‘"
"\\.nims" = "ğŸ‘‘"
"\\.coffee" = "î˜›"
"\\.mustache" = "î˜"
"\\.hbs" = "î˜"
"\\.conf" = "âš™"
"\\.ini" = "âš™"
"\\.yml" = "âš™"
"\\.yaml" = "âš™"
"\\.toml" = "âš™"
"\\.mk" = "âš™"
"\\.twig" = "î˜œ"
"\\.cpp" = "î˜"
"\\.c++" = "î˜"
"\\.cxx" = "î˜"
"\\.cc" = "î˜"
"\\.cp" = "î˜"
"\\.c" = "î˜"
"\\.cs" = "ï š"
"\\.h" = "ïƒ½"
"\\.hh" = "ïƒ½"
"\\.hpp" = "ïƒ½"
"\\.hxx" = "ïƒ½"
"\\.hs" = "î˜Ÿ"
"\\.lhs" = "î˜Ÿ"
"\\.nix" = "ïŒ“"
"\\.lua" = "î˜ "
"\\.java" = "îœ¸"
"\\.sh" = "î•"
"\\.fish" = "î•"
"\\.bash" = "î•"
"\\.zsh" = "î•"
"\\.ksh" = "î•"
"\\.csh" = "î•"
"\\.awk" = "î•"
"\\.sed" = "î•"
"\\.m4" = "ï€µ"
"\\.cmd" = "î˜©"
"\\.bat" = "î˜©"
"\\.ps1" = "îœ"
"\\.ml" = "Î»"
"\\.mli" = "Î»"
"\\.diff" = "îœ¨"
"\\.db" = "îœ†"
"\\.odb" = "ï‡€"
"\\.sql" = "îœ†"
"\\.sqlite" = "îœ†"
"\\.dump" = "îœ†"
"\\.mongo" = "î¤"
"\\.rdb" = "î­"
"\\.clj" = "î¨"
"\\.cljc" = "î¨"
"\\.cljs" = "îª"
"\\.edn" = "îª"
"\\.scala" = "îœ·"
"\\.go" = "î˜¦"
"\\.dart" = "î˜"
"\\.xul" = "î…"
"\\.sln" = "îœŒ"
"\\.suo" = "îœŒ"
"\\.pl" = "î©"
"\\.pm" = "î©"
"\\.t" = "î©"
"\\.rss" = "î˜™"
"\\.f#" = "î§"
"\\.fsscript" = "î§"
"\\.fsx" = "î§"
"\\.fs" = "î§"
"\\.fsi" = "î§"
"\\.rs" = "î¨"
"\\.rlib" = "î¨"
"\\.d" = "î¯"
"\\.erl" = "î±"
"\\.hrl" = "î±"
"\\.ex" = "î˜­"
"\\.exs" = "î˜­"
"\\.eex" = "î˜­"
"\\.leex" = "î˜­"
"\\.heex" = "î˜­"
"\\.vim" = "î˜«"
"\\.ai" = "î´"
"\\.psd" = "î¸"
"\\.psb" = "î¸"
"\\.ts" = "î˜¨"
"\\.tsx" = "îº"
"\\.jl" = "î˜¤"
"\\.pp" = "ï’™"
"\\.vue" = "ïµ‚"
"\\.elm" = "î˜¬"
"\\.swift" = "î•"
"\\.xcplayground" = "î•"
"\\.tex" =  "ï­¨"
"\\.r" = "ó°Ÿ”"
"\\.R" = "ï³’"
"\\.rproj" = "ï«…"
"\\.sol" = "ï²¹"
"\\.apk" = "ï…»"
"\\.xapk" = "ï…»"
"\\.pem" = "ï Š"
"gruntfile.coffee" = "î˜‘"
"gruntfile.js" = "î˜‘"
"gruntfile.ls" = "î˜‘"
"gulpfile.coffee" = "î˜"
"gulpfile.js" = "î˜"
"gulpfile.ls" = "î˜"
"mix.lock" = "î˜­"
"dropbox" = "îœ‡"
"\\.ds_store" = "âš™"
"\\.git" = "îœ‚"
"\\.gitconfig" = "ï‡“"
"\\.gitignore" = "ï‡“"
"\\.gitattributes" = "ï‡“"
"\\.gitlab-ci.yml" = "ïŠ–"
"bashrc" = "âš™"
"\\.zshrc" = "âš™"
"\\.zshenv" = "âš™"
"\\.zprofile" = "âš™"
"\\.vimrc" = "î˜«"
"\\.gvimrc" = "î˜«"
"_vimrc" = "î˜«"
"_gvimrc" = "î˜«"
"\\.bashprofile" = "âš™"
"favicon.ico" = "î˜£"
"license" = "ğŸ“œ"
"licence" = "ğŸ“œ"
"node_modules" = "îœ˜"
"react.jsx" = "îº"
"procfile" = "î˜‡"
"dockerfile" = "î°"
"docker-compose.yml" = "î°"
"rakefile " = "î‘"
"config.ru" = "î‘"
"gemfile" = "î‘"
"makefile" = "âš™"
"cmakelists.txt" = "âš™"
"robots.txt" = "ğŸ¤–"
"\\.tar" = "î¬©"
"\\.tgz" = "î¬©"
"\\.arc" = "î¬©"
"\\.arj" = "î¬©"
"\\.taz" = "î¬©"
"\\.lha" = "î¬©"
"\\.lz4" = "î¬©"
"\\.lzh" = "î¬©"
"\\.lzma" = "î¬©"
"\\.tlz" = "î¬©"
"\\.txz" = "î¬©"
"\\.tzo" = "î¬©"
"\\.t7z" = "î¬©"
"\\.zip" = "î¬©"
"\\.z" = "î¬©"
"\\.dz" = "î¬©"
"\\.gz" = "î¬©"
"\\.lrz" = "î¬©"
"\\.lz" = "î¬©"
"\\.lzo" = "î¬©"
"\\.xz" = "î¬©"
"\\.zst" = "î¬©"
"\\.tzst" = "î¬©"
"\\.bz2" = "î¬©"
"\\.bz" = "î¬©"
"\\.tbz" = "î¬©"
"\\.tbz2" = "î¬©"
"\\.tz" = "î¬©"
"\\.deb" = "î¬©"
"\\.rpm" = "î¬©"
"\\.jar" = "î¬©"
"\\.war" = "î¬©"
"\\.ear" = "î¬©"
"\\.sar" = "î¬©"
"\\.rar" = "î¬©"
"\\.alz" = "î¬©"
"\\.ace" = "î¬©"
"\\.zoo" = "î¬©"
"\\.cpio" = "î¬©"
"\\.7z" = "î¬©"
"\\.rz" = "î¬©"
"\\.cab" = "î¬©"
"\\.wim" = "î¬©"
"\\.swm" = "î¬©"
"\\.dwm" = "î¬©"
"\\.esd" = "î¬©"
"\\.xpi" = "î¬©"
"\\.jpg" = "ï€¾"
"\\.jpeg" = "ï€¾"
"\\.jpe" = "ï€¾"
"\\.mjpg" = "ï€¾"
"\\.mjpeg" = "ï€¾"
"\\.jxl" = "ï€¾"
"\\.svg" = "ó°²"
"\\.svgz" = "ó°²"
"\\.bmp" = "ó°ˆŸ"
"\\.pbm" = "ó°ˆŸ"
"\\.pgm" = "ó°ˆŸ"
"\\.ppm" = "ó°ˆŸ"
"\\.tga" = "ó°ˆŸ"
"\\.xbm" = "ó°ˆŸ"
"\\.xpm" = "ó°ˆŸ"
"\\.tif" = "ó°ˆŸ"
"\\.tiff" = "ó°ˆŸ"
"\\.png" = "ó°ˆŸ"
"\\.webp" = "ó°ˆŸ"
"\\.mng" = "ó°ˆŸ"
"\\.pcx" = "ó°ˆŸ"
"\\.ico" = "ó°ˆŸ"
"\\.gif" = "ó°µ¸"
"\\.mov" = "ï”¬"
"\\.mpg" = "ï”¬"
"\\.mpeg" = "ï”¬"
"\\.m2v" = "ï”¬"
"\\.mkv" = "ï”¬"
"\\.webm" = "ï”¬"
"\\.ogm" = "ï”¬"
"\\.mp4" = "ï”¬"
"\\.m4v" = "ï”¬"
"\\.mp4v" = "ï”¬"
"\\.vob" = "ï”¬"
"\\.qt" = "ï”¬"
"\\.nuv" = "ï”¬"
"\\.wmv" = "ï”¬"
"\\.asf" = "ï”¬"
"\\.rm" = "ï”¬"
"\\.rmvb" = "ï”¬"
"\\.flc" = "ï”¬"
"\\.avi" = "ï”¬"
"\\.fli" = "ï”¬"
"\\.flv" = "ï”¬"
"\\.gl" = "ï”¬"
"\\.dl" = "ï”¬"
"\\.xcf" = "ï”¬"
"\\.xwd" = "ï”¬"
"\\.yuv" = "ï”¬"
"\\.cgm" = "ï”¬"
"\\.emf" = "ï”¬"
"\\.ogv" = "ï”¬"
"\\.ogx" = "ï”¬"
"\\.kdenlive" = "ó°"
"\\.prproj" = "ó°"
"\\.wav" = "ğŸµ"
"\\.aac" = "ğŸµ"
"\\.au" = "ğŸµ"
"\\.flac" = "ğŸµ"
"\\.m4a" = "ğŸµ"
"\\.mid" = "ğŸµ"
"\\.midi" = "ğŸµ"
"\\.mka" = "ğŸµ"
"\\.mp3" = "ğŸµ"
"\\.mpc" = "ğŸµ"
"\\.ogg" = "ğŸµ"
"\\.ra" = "ğŸµ"
"\\.oga" = "ğŸµ"
"\\.opus" = "ğŸµ"
"\\.spx" = "ğŸµ"
"\\.xspf" = "ğŸµ"
"\\.elf" = "ï‘±"
"\\.exe" = "îœ"
"\\.appx" = "îœ"
"\\.msi" = "îœ"
"\\.app" = "ï…¹"
"\\.pdf" = "ïœ¤"
"\\.ps" = "ïœ¤"
"\\.txt" = "ï…œ"
"\\.csv" = "ó°±¾"
"\\.tsv" = "ó°±¾"
"\\.djvu" = "ğŸ“š"
"\\.epub" = "ğŸ“š"
"\\.torrent" = "ğŸ“¥"
"\\.magnet" = "ğŸ§²"
"\\.lrc" = "ğŸ¤"
"\\.kar" = "ğŸ¤"
"\\.src" = "ğŸ’¬"
"\\.gpg" = "ğŸ”"
"\\.ssh" = "ğŸ”‘"
"\\.key" = "ğŸ”‘"
"\\.rsa" = "ğŸ”‘"
"\\.pem" = "ğŸ”‘"
"\\.sig" = "ğŸªª"
"\\.asc" = "ğŸ•µ"
"\\.manifest" = "ğŸ“œ"
"\\.log" = "ğŸ“™"
"\\.xopp" = "ğŸ“”"
"\\.iso" = "ğŸ“€"
"\\.img" = "ğŸ“€"
"\\.bib" = "ğŸ“"
"\\.nfo" = "ïš"
"\\.info" = "ïš"
"\\.m" = "ğŸ“Š"
"\\.ods" = "ğŸ“—"
"\\.xls" = "ğŸ“—"
"\\.xlsx" = "ğŸ“—"
"\\.odt" = "ğŸ“˜"
"\\.doc" = "ğŸ“˜"
"\\.docx" = "ğŸ“˜"
"\\.odp" = "ğŸ“•"
"\\.ppt" = "ğŸ“•"
"\\.pptx" = "ğŸ“•"
"\\.odg" = "ğŸ–¼"
"\\.krita" = "ğŸ–Œ"
"\\.kra" = "ğŸ–Œ"
"\\.xcf" = "ğŸ–Œ"
"\\.eml" = "ğŸ“§"
"\\.mom" = "âœ "
"\\.me" = "âœ"
"\\.ms" = "âœ"
"\\.groff" = "âœ"
"\\.tbl" = "âœ"
"\\.pic" = "âœ"
"\\.blend" = "ï–ª"
"\\.ffpreset" = "ïœª"
"\\.bak" = "ğŸ—ƒ"
"\\.desktop" = "ğŸ–¥"
"\\.z64" = "ğŸ®"
"\\.v64" = "ğŸ®"
"\\.n64" = "ğŸ®"
"\\.gba" = "ğŸ®"
"\\.nes" = "ğŸ®"
"\\.gdi" = "ğŸ®"
"\\.gam" = "ğŸ®"
"\\.sav" = "ğŸ®"
"\\.scm" = "ğŸ®"
"\\.bin" = "ğŸ®"
"\\.psv" = "ğŸ®"
"\\.rom" = "ğŸ®"
"\\.xex" = "ğŸ®"
"\\.jrz" = "ğŸ®"
"\\.efi" = "ï„‚"
